# Generated by Django 4.2.1 on 2023-08-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pin', '0002_pins_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='image',
            field=models.ImageField(null=True, upload_to='pin/'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
