# Generated by Django 4.2.1 on 2023-08-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_kategori_pins_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='profile_image',
        ),
    ]
