# Generated by Django 4.2.1 on 2023-08-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0007_product_remove_comment_created_at_remove_comment_pin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pinsc',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='pins',
        ),
    ]
